######################################################################
# Automatically generated by qmake (3.0) ?? 10? 7 20:01:57 2018
######################################################################

INCLUDEPATH += .

INCLUDEPATH += ../sound/OggVorbis ../sound/OggVorbis/vorbissrc

DEFINES += _HARMATTAN_RENDERER_LOCAL_OGG_LIB

# Input
HEADERS += ../sound/snd_local.h \
           ../sound/sound.h
SOURCES += ../sound/snd_cache.cpp \
           ../sound/snd_decoder.cpp \
           ../sound/snd_efxfile.cpp \
           ../sound/snd_emitter.cpp \
           ../sound/snd_shader.cpp \
           ../sound/snd_system.cpp \
           ../sound/snd_wavefile.cpp \
           ../sound/snd_world.cpp


HEADERS += ../sound/OggVorbis/ogg/ogg.h \
           ../sound/OggVorbis/ogg/os_types.h \
           ../sound/OggVorbis/vorbis/codec.h \
           ../sound/OggVorbis/vorbis/vorbisenc.h \
           ../sound/OggVorbis/vorbis/vorbisfile.h \
           ../sound/OggVorbis/vorbissrc/backends.h \
           ../sound/OggVorbis/vorbissrc/bitrate.h \
           ../sound/OggVorbis/vorbissrc/codebook.h \
           ../sound/OggVorbis/vorbissrc/codec_internal.h \
           ../sound/OggVorbis/vorbissrc/envelope.h \
           ../sound/OggVorbis/vorbissrc/highlevel.h \
           ../sound/OggVorbis/vorbissrc/lookup.h \
           ../sound/OggVorbis/vorbissrc/lookup_data.h \
           ../sound/OggVorbis/vorbissrc/lpc.h \
           ../sound/OggVorbis/vorbissrc/lsp.h \
           ../sound/OggVorbis/vorbissrc/masking.h \
           ../sound/OggVorbis/vorbissrc/mdct.h \
           ../sound/OggVorbis/vorbissrc/misc.h \
           ../sound/OggVorbis/vorbissrc/os.h \
           ../sound/OggVorbis/vorbissrc/psy.h \
           ../sound/OggVorbis/vorbissrc/registry.h \
           ../sound/OggVorbis/vorbissrc/scales.h \
           ../sound/OggVorbis/vorbissrc/smallft.h \
           ../sound/OggVorbis/vorbissrc/window.h \
           ../sound/OggVorbis/vorbissrc/modes/floor_all.h \
           ../sound/OggVorbis/vorbissrc/modes/psych_11.h \
           ../sound/OggVorbis/vorbissrc/modes/psych_16.h \
           ../sound/OggVorbis/vorbissrc/modes/psych_44.h \
           ../sound/OggVorbis/vorbissrc/modes/psych_8.h \
           ../sound/OggVorbis/vorbissrc/modes/residue_16.h \
           ../sound/OggVorbis/vorbissrc/modes/residue_44.h \
           ../sound/OggVorbis/vorbissrc/modes/residue_44u.h \
           ../sound/OggVorbis/vorbissrc/modes/residue_8.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_11.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_16.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_22.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_32.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_44.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_44u.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_8.h \
           ../sound/OggVorbis/vorbissrc/modes/setup_X.h \
           ../sound/OggVorbis/vorbissrc/books/coupled/res_books_stereo.h \
           ../sound/OggVorbis/vorbissrc/books/floor/floor_books.h \
           ../sound/OggVorbis/vorbissrc/books/uncoupled/res_books_uncoupled.h

SOURCES += ../sound/OggVorbis/oggsrc/bitwise.c \
           ../sound/OggVorbis/oggsrc/framing.c \
           ../sound/OggVorbis/vorbissrc/analysis.c \
           # ../sound/OggVorbis/vorbissrc/barkmel.c \
           ../sound/OggVorbis/vorbissrc/bitrate.c \
           ../sound/OggVorbis/vorbissrc/block.c \
           ../sound/OggVorbis/vorbissrc/codebook.c \
           ../sound/OggVorbis/vorbissrc/envelope.c \
           ../sound/OggVorbis/vorbissrc/floor0.c \
           ../sound/OggVorbis/vorbissrc/floor1.c \
           ../sound/OggVorbis/vorbissrc/info.c \
           ../sound/OggVorbis/vorbissrc/lookup.c \
           ../sound/OggVorbis/vorbissrc/lpc.c \
           ../sound/OggVorbis/vorbissrc/lsp.c \
           ../sound/OggVorbis/vorbissrc/mapping0.c \
           ../sound/OggVorbis/vorbissrc/mdct.c \
           ../sound/OggVorbis/vorbissrc/psy.c \
           # OggVorbis/vorbissrc/psytune.c \
           ../sound/OggVorbis/vorbissrc/registry.c \
           ../sound/OggVorbis/vorbissrc/res0.c \
           ../sound/OggVorbis/vorbissrc/sharedbook.c \
           ../sound/OggVorbis/vorbissrc/smallft.c \
           ../sound/OggVorbis/vorbissrc/synthesis.c \
           # ../sound/OggVorbis/vorbissrc/tone.c \
           ../sound/OggVorbis/vorbissrc/vorbisenc.c \
           ../sound/OggVorbis/vorbissrc/vorbisfile.c \
           ../sound/OggVorbis/vorbissrc/windowvb.c
